# Generated by Django 3.2.4 on 2021-06-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_way', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
